version = 1

[[annotations]]
path = ".gitignore"
SPDX-FileCopyrightText = "2025 Oscar Bender-Stone <oscar-bender-stone@protonmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "html/eng/index.html"
SPDX-FileCopyrightText = "2025 Oscar Bender-Stone <oscar-bender-stone@protonmail.com>"
SPDX-License-Identifier = "CC-BY-SA-4.0"
