# SPDX-FileCopyrightText: 2025 Oscar Bender-Stone <oscar-bender-stone@protonmail.com>
# SPDX-License-Identifier: CC0-1.0

# frozen_string_literal: true

source "https://rubygems.org"

gem "asciidoctor", "~> 2.0"
