version = 1

[[annotations]]
path = ".gitignore"
SPDX-FileCopyrightText = "2025 Oscar Bender-Stone <oscar-bender-stone@protonmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "uv.lock"
SPDX-FileCopyrightText = "2025 Oscar Bender-Stone <oscar-bender-stone@protonmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ".python-version"
SPDX-FileCopyrightText = "2025 Oscar Bender-Stone <oscar-bender-stone@protonmail.com>"
SPDX-License-Identifier = "CC0-1.0"
